# Generated by Django 2.0 on 2018-06-05 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='likecount',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='likerecord',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='likerecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='LikeCount',
        ),
        migrations.DeleteModel(
            name='LikeRecord',
        ),
    ]
